### ISSUE TITLE
to child() or not

### ISSUE THREAD

**Issue by thisbejim** [thisbejim/Pyrebase#10]
With #9 we can more easily pass in variables for paths and let pyrebase build that path. Given that queries are now more aligned with the javascript library, would it also make sense to chain child paths in a similar way? e.g. ```python admin.query("users").child("Marty").get()```

The benefit is that it is again more explicit. Additionally, if a user tries out pyrebase and are familiar with the javascript way of handling firebase then it might be easier for them to get started. 

So in the end you could build paths three way:
 ```python admin.query("users/Marty").get()```
 ```python admin.query("users", "Marty").get()```
 ```python admin.query("users").child("Marty").get()```

Is this flexible or confusing? Not sure yet.

**Comment by Tenzer** [comment]
Since it would be really easy to implement, I think it makes sense to support all three. Wouldn't it however make a collision with the `Firebase.child` parameter? That could however be renamed to `path` instead.

If that was done, the `child()` method would basically just be:

```python
def child(self, path):
    self.path += "/{}".format(path.strip("/"))
```

The `strip()` is optional :)

**Comment by thisbejim** [comment]
Child() added with 80e2bfcac3e13198e2c5491cc4701c274a1d8464
