### ISSUE TITLE
Is there a way to prevent the initial bulk stream from arriving at all?

### ISSUE THREAD

**Issue by aligajani** [thisbejim/Pyrebase#123]
When using the Streaming Handler, the first stream contains all the big data from the node, which is expensive on network and bandwidth. I am only interested in the individual stream messages, that do arrive afterwards, but I really want to prevent the first bulk of messages arriving at all. Anyway to prevent that from coming at all?

**Comment by thisbejim** [comment]
Hi @aligajani, returning all the initial data when opening a stream is the expected behaviour (this is the data that Firebase sends along). However, there is [an issue](https://github.com/thisbejim/Pyrebase/issues/115) where reauthenticating and restarting a stream causes all that data to hit the stream handler a second time. We can't stop Firebase from sending that information but we can filter it out, follow along with the progress of that issue to see when this is fixed.
