### ISSUE TITLE
Pyrebase and papertrail together: KeyError: 'hostname' 

### ISSUE THREAD

**Issue by dauledk** [thisbejim/Pyrebase#136]
Hi everyone!

Does anyone have experience with using Pyrebase together with papertrail?

I am trying to do this as simple as possible, but keep getting this error: 
`KeyError: 'hostname'`
From the following Traceback:
  ```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/handlers.py", line 884, in emit
    msg = self.format(record)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py", line 828, in format
    return fmt.format(record)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py", line 568, in format
    s = self.formatMessage(record)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py", line 537, in formatMessage
    return self._style.format(record)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py", line 381, in format
    return self._fmt % record.__dict__
```

The papertrail code follows the "[Generic Python app](http://help.papertrailapp.com/kb/configuration/configuring-centralized-logging-from-python-apps/#method-b-use-pythons-sysloghandler)" example. The pyrebase code uses the stream handler: 

```
firebase = pyrebase.initialize_app(config)
db = firebase.database()

def stream_handler(message):
    event = message['event']

play_stream = db.child("Settings/sound/skaale").stream(stream_handler) 
```

Both pieces of codes are working independently.

**Comment by dauledk** [comment]
Apparently (or at least I think), it is a bug in requests - used by pyrebase. According to [this](https://github.com/kennethreitz/requests/issues/1889) issue. At least the fix changing the log level to error in the generic Python app example does "fix" the problem.

**Comment by ExplodingCabbage** [comment]
Not a bug in `requests`, and not one in Pyrebase either. The [Generic Python app](https://help.papertrailapp.com/kb/configuration/configuring-centralized-logging-from-python-apps/#generic-python-app) instructions in Papertrail's Knowledge Base are broken. They instruct you to add a filter to the root logger that adds a `hostname` attribute to log records, and a handler to the root logger with a formatter that uses the `hostname` attribute. However, a quirk of Python's logging module is that while a logger's handlers are invoked for log records logged by descendant loggers, its *filters* are not applied to such records. Consequently, with Papertrail's currently documented setup, any time that a child logger tries to log *anything* at a level equal to or higher than the root logger's log level, the formatter tries to use a `hostname` attribute that doesn't exist and everything explodes - as you've discovered. Since creating a child logger is a standard practice for libraries in Python, this bug renders Papertrail's "generic Python app" example setup incompatible with basically the entire ecosystem of Python libraries.

Fortunately, there's a trivial fix: instead of doing `logger.addFilter(f)` as shown in Papertrail's docs, do `syslog.addFilter(f)` - i.e. add the filter to the *handler* instead of the *logger*. I've just emailed Papertrail explaining this to them and suggesting that they make the change.
