### ISSUE TITLE
Fetch data from the list created with .each()

### ISSUE THREAD

**Issue by efialtisgr** [thisbejim/Pyrebase#29]
Hi, first of all thanks for the Pyrebase i love it !

btw i have a small issues you may can help me.
I m new in firebase, and i would like to store data in firebase but before the push i would like if the data are already in firebase , if they exist then i dont want to push them.

I was trying to fetch all the val using the:

db = firebase.database().child('xtrmp')
matches = db.get(user['idToken'])
for i in matches.each():
        xtrmData = i.val()
        print xtrmData

this gives me the list i would like  ->
{u'date': u'2016-06-01T12:00:00', u'drawOdds': u'7.50', u'homeOdds': u'1.17', u'awayOdds': u'8.85', u'match': u'FC BULLEEN LIONS vs. SOUTH MELBOURNE'}

My question is how can i get the match val so i can check if there is in db before push ?

Or there is another way to achieve that ? 

Thanks for your time and your help :)

**Comment by thisbejim** [comment]
Hi efialtisgr, I'm glad you are finding Pyrebase useful!

There are a couple of ways to approach this problem. 

The first is to set up an [index](https://firebase.google.com/docs/database/security/indexing-data#defining_data_indexes) in your security rules to allow for complex queries on specific properties in your database. In this example we'll be querying the ```match``` property, so our security rules might look something like this:
```
{
  "rules": {
    ".read": "true",
    ".write": "true",
    "xtrmp": {
      ".indexOn": ["match"]
    }
  }
}
```
Now we can run a query to check if a child with the ```match``` type of "FC BULLEEN LIONS vs. SOUTH MELBOURNE" exists, for example:
```
db = firebase.database()
matches = db.child("xtrmp").order_by_child("match").equal_to("FC BULLEEN LIONS vs. SOUTH MELBOURNE").get(user["idToken"])
if not matches.val():
    # data doesn't exist, we now know can push the data
```

That is one way to solve this. 

Another way to solve this problem is to save your data with custom made keys, rather than keys generated by firebase. Let's pretend we save all our matches with keys that follow the naming scheme of ```"TEAMvsTEAM"```, for example ```"BLvsSM"```:
```
db.child("xtrmp").child("BLvsSM").set(data, user["idToken"])
```
Now we'll be able to easily check if data exists in these locations, for example:
```
match = db.child("xtrmp").child("BLvsSM").get(user["idToken"])
if not match.val():
    # data doesn't exist, we now know can push the data
```
