### ISSUE TITLE
Stream ignores messages with path '/'

### ISSUE THREAD

**Issue by jsanchezgarcia** [thisbejim/Pyrebase#45]
I've observed some strange behaviour with the Stream listener. Looking at the following code I noticed that Pyrebase stream only triggers if msg_data['path'] != '/'. What's the reason for this?

```
def start_stream(self, url, stream_handler):
        self.sse = ClosableSSEClient(url)
        for msg in self.sse:
            msg_data = json.loads(msg.data)
            # don't return initial data
            if msg_data and msg_data['path'] != '/':
                msg_data["event"] = msg.event
                stream_handler(msg_data)
```

The way I understand it, this constraint will ignore updates on a resource we're watching. For example, the following stream will not see updates happening in 'resource1', but will see the ones in its children.
`my_stream = db.child("resource1").stream(stream_handler)`

**Comment by thisbejim** [comment]
Hi @jsanchezgarcia, thanks for bringing this to my attention! 

So the original reason for this was a bit opinionated on my part: When you set up the stream the first thing it does is download everything that is already on that ref, so if you want to stream "posts" you first have to deal with all the posts that already exist before you can just move on to the actual streaming. This is something that I have never wanted when streaming (you can just use the get() method for that). 

However, I was not aware of this side effect and would rather not cripple streaming, so this is fixed with 1ad60e28f782a9db321b6232773f23cb96b020c0 and is available in the new version of Pyrebase.
