### ISSUE TITLE
Occasional Permission Denied

### ISSUE THREAD

**Issue by josefmonje** [thisbejim/Pyrebase#51]
I __occasionally__ get this permission denied error and resolve it by restarting my local server... until it happens again. What could be causing this?

```
Traceback (most recent call last):
  File "/Users/.../lib/python3.5/site-packages/pyrebase/pyrebase.py", line 353, in raise_detailed_error
    request_object.raise_for_status()
  File "/Users/.../lib/python3.5/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://....firebaseio.com/....json

During handling of the above exception, another exception occurred:

  File "/Users/.../lib/python3.5/site-packages/pyrebase/pyrebase.py", line 232, in set
    raise_detailed_error(request_object)
  File "/Users/.../lib/python3.5/site-packages/pyrebase/pyrebase.py", line 356, in raise_detailed_error
    raise HTTPError(e, request_object.text)
requests.exceptions.HTTPError: [Errno 403 Client Error: Forbidden for url: https://....firebaseio.com/....json] {
  "error" : "Permission denied."
}
```
I'm on the latest version of Pyrebase and on Python 3.5, using a Firebase service account.

**Comment by teodorgarzdin** [comment]
I can confirm this issue. I'm getting the same error after upgrading to Python 3.5 and the newest Pyrebase. Also using a service account.

**Comment by teodorgarzdin** [comment]
I can confirm this issue. I'm getting the same error after upgrading to Python 3.5 and the newest Pyrebase. Also using a service account.

```
Traceback (most recent call last):
  File "*****/controllers/products.py", line 56, in fetch_products
    db.child("products").child(locale).set(db_data)
  File "*****/lib/pyrebase/pyrebase.py", line 232, in set
    raise_detailed_error(request_object)
  File "*****/lib/pyrebase/pyrebase.py", line 356, in raise_detailed_error
    raise HTTPError(e, request_object.text)
HTTPError: [Errno 401 Client Error: Unauthorized for url: ***********] {
  "error" : "Permission denied"
}
```

**Comment by josefmonje** [comment]
@teodorgarzdin are you making multiple requests?

**Comment by teodorgarzdin** [comment]
@josefmonje I have 10 cron jobs setup 1 minute from one another. Each one writes two things to the database.

**Comment by josefmonje** [comment]
Maybe it's a throttling issue? I mirror several models to firebase. One of the models creates an instance of another model that is also mirrored to firebase.

**Comment by bazookon** [comment]
+1 same problem, with appengine! python 2.7 i can't use in production!

**Comment by jayhuang75** [comment]
+1 have the same problem.

**Comment by josefmonje** [comment]
I resolved my issue by importing a function that returns a new instance of pyrebase.initialize_app() app, and not initializing it once and using that connection throughout my app which was what i did previously. This solved the successive permission denied errors that required me to restart my app. This may mean that the connection expires.

I still get occasional permission denied errors that I suspect is caused by database locking. But it no longer is the "cause of death".

@teodorgarzdin @bazookon @jayhuang75

**Comment by bazookon** [comment]
Works! thanks!

**Comment by thisbejim** [comment]
Hi everyone (@josefmonje @teodorgarzdin @bazookon @jayhuang75 )! 

Thank you for waiting patiently and coming up with some alternative solutions (thanks @josefmonje) until I could find the time to look into the issue.

## Service Account
So the first thing I noticed (that is sort of seperate from this issue but also causes permission denied errors) is that when generating a service account we have to make sure the role is set to "Owner":

![Owner](http://i.imgur.com/WtK4GCe.jpg)

## Pyrebase
The second thing is the code in Pyrebase. Reading the [oauth2 docs for service accounts](http://oauth2client.readthedocs.io/en/latest/source/oauth2client.service_account.html) we find: 

>This credential does not require a flow to instantiate because it represents a two legged flow, and therefore has all of the required information to generate and refresh its own access tokens.

So really we should be able to refresh tokens automatically and not run into any permission errors.

The error in the Pyrebase code is that when we were intialize Pyrebase the access_token was cached (instead of generating it dynamically for each api call) which meant we were eventually using stale access tokens for our api calls.

The offending code:
```
self.access_token = self.credentials.get_access_token()
```
So rather than caching we directly store the credentials and call ```get_access_token()``` before each api call.

This has been added with e0f7c59fd48a37348136c0dd7b77a9219c22d22b and is now in the newest release of Pyrebase. I've only tested this change with about ~2 hours of operations so if you could all try it out and let me know how it goes that would be great.

Thanks!

**Comment by josefmonje** [comment]
Thanks @thisbejim !

**Comment by tamakisquare** [comment]
@thisbejim: FYI, **"Editor"** role, as opposed to "Owner" role, has sufficient permissions required by the Service Account. This is the exact same role assigned to the Firebase Admin SDK.

**Comment by sorenandersen** [comment]
@thisbejim @tamakisquare "Project Editor" has "edit access to all resources" according to Firebase IAM. I'd like to authenticate with a service account less powerfull, i.e. only allowed access to the realtime database, and in my rules specify `{".write": "auth.uid === 'service-acccount-name'"}`. But it seems like this is not supported? I'm not using Pyrebase but raw REST requests and I cannot even authenticate my service account if it is not in the "Project Editor" role. Any thoughts on this?

**Comment by jayhuang75** [comment]
@sorenandersen I think it's not relative with Pyrebase, you may need to generate a firebase access token for your api call in your front end or in your Middleware! Because for firebase once you setup the access roles! You will need the token!

**Comment by abdullahaftab** [comment]
Hello everyone ! I have almost tried everything but still i am getting error:"Permission denied". Can anyone help me on this?
