### ISSUE TITLE
Error in child("path/path").get() with two level path

### ISSUE THREAD

**Issue by cheve1969** [thisbejim/Pyrebase#61]
In this code:
data = db.child("test").get()
data.each() return a list of Pyre objects

In this code:
data = db.child("test/people").get()
data.each() return a list of dicts, so I can't get the keys.

with another level returns Pyre objects again:
data = db.child("test/people/0").get()
data.each() return a list of Pyre objects

[X] Check that your version of Python is 3.4+ --> python 3.5
[X] Check that you are on the newest version of Pyrebase --> Donwloaded today
[X] Check that Email/password provider is enabled in your Firebase dashboard under Auth -> Sign In Method. --> Works for read and writes

**Comment by thisbejim** [comment]
Thanks for raising this issue @cheve1969, interesting stuff! Will take a look at it when I find the time.

**Comment by thisbejim** [comment]
@cheve1969 can you give and example of what your desired response would be when querying the ```"test/people"``` endpoint? Also, are the keys used for this endpoint sequential numbers (0,1,2,3)? If so Firebase will return a list rather than a dictionary that uses those numbers for keys.

**Comment by cheve1969** [comment]
I expect to get Pyre object when I call each() so I can iterate over items getting key and val:

```
data = db.child("test/people").get()
for x in data.each():
    print( x.key(), x.val() )
```

At this moment data.each() is returning a python dict, which is not the documented behavior and I can´t get the keys.

**Comment by thisbejim** [comment]
Hi @chece1969, can you please go to your Firebase console and post the first couple of keys of items at "test/people"? 

The reason being we need to check if Firebase itself (not Pyrebase) is returning a list instead if a dictionary.

For example if we have the following data at "test/people" we should get the response you are expecting:

'''
jsheif2472: {
  name: "john"
},
kfn46jsbi84: {
  name: "henry"
}
''' 

However if our keys are a sequence of numbers like this:
'''
0: {
  name: "john"
},
1: {
  name: "henry"
}
''' 
...then Firebase will actually just return a list that includes no keys, for example:

'''
[{name:"john"}, {name: "henry"}]
'''
And in this case Pyrebase can't actually get the proper keys because they were never sent.

If you could help me with that extra info that would be really great, thanks.

**Comment by cheve1969** [comment]
My keys are numbers.
I was thinking that firebase was using that keys as string (converting 0 to "0"), if those are numbers I don't need the keys.
That make sense.

**Comment by thisbejim** [comment]
Good to know, thanks for the extra info @cheve1969 it was really helpful.

So I've double checked the behaviour of the javascript api and pyrebase is not following expected behaviour. 

If we have the following data:
```
0: {
  name: "john"
},
1: {
  name: "henry"
}
```
Here is the behaviour when using the official javascript library:
```
database.ref('test').child('people').once('value', function(snap) {
  snap.val() // [{name: "john"}, {name: "henry"}]
  snap.key // people
  snap.forEach(function(person) {
    person.val() // { name: "john" }
    person.key // 0
  });
});
```

And here is pyrebase's behaviour:
```
data = db.child('test').child('people').get()
data.val() # AttributeError: 'dict' object has no attribute 'key'
data.key() # people
for person in data.each():
    person.val() # AttributeError: 'dict' object has no attribute 'val'
    person.key() # AttributeError: 'dict' object has no attribute 'key'
```

So definitely some changes to make.

**Comment by thisbejim** [comment]
OK, added this with cc437b05d299f408b168b53102434d8620835b78

Firebase javascript:
```
database.ref('test').child('people').once('value', function(snap) {
  snap.val() // [{name: "john"}, {name: "henry"}]
  snap.key // people
  snap.forEach(function(person) {
    person.val() // { name: "john" }
    person.key // 0
  });
});
```
Pyrebase:
```
data = db.child('test').child('people').get()
data.val() # [{name: "john"}, {name: "henry"}]
data.key() # people
for person in data.each():
    person.val() # { name: "john" }
    person.key() # 0
```

Thanks for all your help and discovering this bug @cheve1969!

**Comment by cheve1969** [comment]
Thanks to you. With pyrebase was really easy to populate my firebase real time database with data from other database.

**Comment by FadhlanR** [comment]
Thak's because this discussion, i have solution.

But i have another problem, when i try to get all data child, i get some object that not exist in firebase but exist in return value. And that object has None or null value. May be you can help me.
