### ISSUE TITLE
Refresh Service Account Auth

### ISSUE THREAD

**Issue by aldenks** [thisbejim/Pyrebase#62]
Hello, thanks for making pyrebase!

I am using service account authentication and get 400s after an hour. I see the `refresh` method, but am not sure how to use that with a service account. Is there any way to do this?

**Comment by thisbejim** [comment]
Glad you are enjoying it @aldenks, thanks for dropping by! 

The refresh method is only for user accounts so you don't have to worry about that but hmmmmm automatic token refresh for service accounts should have been fixed with e0f7c59fd48a37348136c0dd7b77a9219c22d22b.

I'm sure you are but I just have to check that you are on the newest version of Pyrebase?

**Comment by aldenks** [comment]
Oh man, facepalm. I had recently updated from 3.0.8 but hadn't pushed that change to production.  Sorry for waisting your time!

**Comment by thisbejim** [comment]
No problem at all @aldenks, happy coding!
